- name: Installing open-iscsi
  become: true
  ansible.builtin.apt:
    name:
      - open-iscsi
      - "linux-modules-extra-{{ ansible_kernel }}"
    update_cache: true

- name: Configuring initramfs for iSCSI boot
  become: true
  ansible.builtin.lineinfile:
    path: /etc/iscsi/iscsi.initramfs
    create: true
    line: ISCSI_AUTO=true
  notify: Update initramfs

- name: Add NIC modules to the initramfs
  become: true
  ansible.builtin.lineinfile:
    path: /etc/initramfs-tools/modules
    create: true
    line: "{{ module }}"
  loop:
    - bnxt_en
    - igb
  loop_control:
    loop_var: module
  notify: Update initramfs
  when:
    - ansible_distribution_major_version | int == 18

- name: Disabling cloud-init network configuration
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/default/grub.d/99-storpool-lab.cfg
    create: yes
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT'
