- name: Adding required dracut modules
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/dracut.conf.d/iscsi-boot.conf
    line: add_dracutmodules+="network iscsi"
    create: yes
  notify: Rebuild dracut image

- name: Configuring GRUB kernel command line
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT rd.iscsi.firmware=1 ip={{ "eth0:dhcp" if (ansible_distribution_major_version | int) <= 7 else "single-dhcp" }}"'
  notify: Rebuild GRUB configuration
