- name: Adding iSCSI dracut configuration
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/dracut.conf.d/iscsi-boot.conf
    line: "{{ item }}"
    create: yes
  notify: Rebuild dracut image
  loop:
    - add_dracutmodules+="network iscsi"
    - install_optional_items+="/etc/udev/rules.d/70-persistent-net.rules /etc/iscsi/iscsid.conf"

- name: Configuring GRUB kernel command line
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT rd.iscsi.firmware=1 ip={{ "mgmt0:dhcp" if (ansible_distribution_major_version | int) <= 7 else "single-dhcp" }}"'
  notify: Rebuild GRUB configuration

- name: Checking if a reboot is required
  become: yes
  ansible.builtin.command: /usr/bin/needs-restarting -r
  register: needs_restarting
  failed_when: false
  changed_when: needs_restarting.rc == 1
  notify: Reboot host
