- name: Adding required dracut modules
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/dracut.conf.d/iscsi-boot.conf
    line: add_dracutmodules+="network iscsi"
    create: yes
  notify: Rebuild dracut image

- name: Creating EFI system partition
  become: yes
  community.general.parted:
    device: /dev/sda
    number: 2
    name: ESP
    part_start: -256MiB
    state: present
    flags:
      - efi
    fs_type: fat32
  notify: Rebuild GRUB configuration

- name: Mounting EFI system partition
  become: yes
  ansible.posix.mount:
    path: /boot/efi/
    src: /dev/sda2
    state: mounted
    fstype: fat32
  notify: Rebuild GRUB configuration

- name: Installing GRUB EFI package
  become: yes
  ansible.builtin.yum:
    name:
      - grub2-efi
      - shim
  notify: Rebuild GRUB configuration

- name: Configuring GRUB kernel command line
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    line: GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT rd.iscsi.firmware=1"
  notify: Rebuild GRUB configuration
