- name: Installing open-iscsi
  become: true
  ansible.builtin.apt:
    name:
      - open-iscsi
      - "linux-modules-extra-{{ ansible_kernel }}"
    update_cache: true

- name: Configuring initramfs for iSCSI boot
  become: true
  ansible.builtin.lineinfile:
    path: /etc/iscsi/iscsi.initramfs
    create: true
    line: ISCSI_AUTO=true
  notify: Update initramfs

- name: Add the bnxt_en module to the initramfs
  become: true
  ansible.builtin.lineinfile:
    path: /etc/initramfs-tools/modules
    create: true
    line: bnxt_en
  notify: Update initramfs
  when:
    - ansible_distribution_major_version | int == 18
