- name: Updating the initramfs
  become: true
  ansible.builtin.command: /usr/sbin/update-initramfs -u
  listen: Update initramfs
  when:
    - ansible_os_family == "Debian"

- name: Rebuilding dracut image
  become: true
  ansible.builtin.command: /usr/bin/dracut -f -v
  listen: Rebuild dracut image
  when:
    - ansible_os_family == "RedHat"

- name: Updating GRUB BIOS configuration
  become: true
  ansible.builtin.command: /usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg
  listen: Rebuild GRUB configuration

- name: Updating GRUB EFI configuration
  become: true
  ansible.builtin.command: "/usr/sbin/grub2-mkconfig -o /boot/efi/EFI/{{ ansible_distribution | lower }}/grub.cfg"
  listen: Rebuild GRUB configuration

- name: Correcting EFI GRUB commands on CentOS 7
  become: true
  ansible.builtin.replace:
    path: "/boot/efi/EFI/{{ ansible_distribution | lower }}/grub.cfg"
    regexp: "{{ item }}16"
    replace: "{{ item }}efi"
  loop:
    - linux
    - initrd
  listen: Rebuild GRUB configuration
  when:
    - ansible_distribution | lower == "centos"
